/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Restaurant newRest=new Restaurant("crispy",4,"##");
        newRest.addReview(new Review("nice","roaa",3));
        newRest.addReview(new Review("clean","ali",4));
        newRest.addReview(new Review("good","Ahmad",2));
        newRest.addReview(new Review("nice","mary",5));
        System.out.println(newRest);
    }
}
