/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.*;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        //System.out.println(new App().getGreeting());
        readFile();
    }
    public static void readFile(){
        int c=0;
        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        InputStream lines = classloader.getResourceAsStream("gates.js");
        try(Scanner scanner=new Scanner(lines)) {

            while (scanner.hasNextLine()) {
                String lineG=scanner.nextLine();
                c++;
                if(!lineG.contains(";")){
                    if(!lineG.contains("{")){
                        if(!lineG.contains("}")){
                            if(!lineG.contains("if")){
                                if(!lineG.contains("else")){
                                    if(!lineG.isEmpty())
                                    {
                                        System.out.println( "Line "+c+": Missing semicolon." );
                                    }

                                }

                            }

                        }

                    }

                }

            }
        }
        catch (Exception e){
            System.err.println(e.getMessage());
    }
}}
