/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.*;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        //System.out.println(new App().getGreeting());
        readFile();
    }
    public static void readFile(){
        File file=new File("gates.js");
        HashSet<String> gateFile=new HashSet<>();
        int c=0;
        try(Scanner scanner=new Scanner(file)) {

            while (scanner.hasNextLine()) {

                gateFile.add(scanner.nextLine());
            }
            String[] gateStr= gateFile.toArray(new String[gateFile.size()]);
            for (int i = 0; i < gateStr.length; i++) {
                c++;
                if(!gateStr[i].contains(";")){
                    if(!gateStr[i].contains("{")){
                        if(!gateStr[i].contains("}")){
                            if(!gateStr[i].contains("if")){
                                if(!gateStr[i].contains("else")){
                                    if(!gateStr[i].isEmpty())
                                    {
                                        System.out.println( "Line "+c+": Missing semicolon." );
                                    }

                                }

                            }

                        }

                    }

                }

            }
        }catch (FileNotFoundException fileNotFoundException){

            System.err.println(fileNotFoundException.getMessage());
        }
    }
}
