/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test public void RestaurantInstanceTest() {
        Restaurant newRestaurant = new Restaurant("crispy", 4,"##");

        String output = "Restaurant name: crispy\n" +
                "Number of stars: 4\n" +
                "Price: ##\n"+
                "Reviews:\n"+
                "[]";
        assertEquals(output, newRestaurant.toString());
    }
    @Test public void ReviewInstanceTest(){
        Review newReview = new Review("good", "roaa",3);
        String output= "{Author: roaa, Body: good, Number of stars: 3}";
        assertEquals(output, newReview.toString());
    }

    @Test
    void addReviewTest(){
        Restaurant newRest=new Restaurant("crispy",4,"##");
        newRest.addReview(new Review("nice","roaa",3));
        newRest.addReview(new Review("clean","ali",4));
        newRest.addReview(new Review("good","Ahmad",2));
        newRest.addReview(new Review("nice","mary",5));
        String output = "Restaurant name: crispy\n" +
                "Number of stars: 3\n" +
                "Price: ##\n"+
                "Reviews:\n"+
                "[{Author: roaa, Body: nice, Number of stars: 3}, {Author: ali, Body: clean, Number of stars: 4}, {Author: Ahmad, Body: good, Number of stars: 2}, {Author: mary, Body: nice, Number of stars: 5}]";
        assertEquals(output, newRest.toString());
    }
}
